### ISSUE TITLE
Editor MVP status.

### ISSUE THREAD

**Issue by mralve** [amethyst/atelier-ui#1]
This editor is in full MVP mode now, we need to make sure that the editor has all the proper planning for the future.

This forum post is where we do the discussions regarding MVP. 
https://community.amethyst.rs/t/atelier-mvp-discussion/1167

Some vitals we need to do **before** we can start any kind of general development.
- [ ] Undo, Redo, Recover, System aka Atelier-Changelog. see #2
- [ ] Properly integrate with Atelier Assets.

**Comment by erlend-sh** [comment]
> Atelier-Changelog
Can you elaborate on what that is? Is it something we'd build into atelier-assets or would it be a standalone library?

**Comment by mralve** [comment]
I'll let @nothingismagick elaborate, it's his brainchild. 🎺

**Comment by mralve** [comment]
Closing this, for now, no more discussions are taking place, I'm now jumping in and start the core work
