### ISSUE TITLE
App is crashing when using tauri.invoke on MSHTML

### ISSUE THREAD

**Issue by Reidond** [amethyst/atelier-ui#10]
**Describe the bug**
App crash

**To Reproduce**

1. Run Quasar and Tauri
2. Click dropdown right to **Debug**
3. In dropdown click **Release**

**Expected behavior**
Invoke Tauri and emit message to console when clicking on Release dropdown button

**Screenshots**
[Screenshot](https://ibb.co/Hgq0mKz)

**Platform (please complete the following information if relevant):**
OS: Windows 10 1903 (OS Build: 18362.10024)
Node: 12.13.0
NPM: 6.12.0
Yarn: 1.19.1
Rust: 1.39.0
Bundle Target:

**Additional context**
File: Index.vue
Line: 133

**Comment by Reidond** [comment]
https://github.com/amethyst/atelier-ui/issues/7

**Comment by nothingismagick** [comment]
So today I am working on rebuilding Tauri to consume web-view from upstream. Wish me luck.

**Comment by nothingismagick** [comment]
This has been resolved today with the rebuild of Tauri to now use EdgeHTML.

You will have to execute the following in an administrator command prompt (while we are still pre-alpha)

```
CheckNetIsolation.exe LoopbackExempt -a -n="Microsoft.Win32WebViewHost_cw5n1h2txyewy"
```
![Screen Shot 2019-11-24 at 22 27 57](https://user-images.githubusercontent.com/35242872/69501918-e3408480-0f09-11ea-9435-1817503a6efe.png)
