### ISSUE TITLE
Maintainer?

### ISSUE THREAD

**Issue by Jaden-Giordano** [amethyst/atelier-ui#14]
I've noticed this isn't getting much attention. Is there any chance we can get someone to look at this maybe once a week, and review PRs? I'd really like to help out, but it's kinda unmotivating to have to wait a couple weeks just for a PR to be reviewed.

**Comment by erlend-sh** [comment]
If @mralve is not available for reviewing these days, we could give you maintainer access to move forward unimpeded.

For Tauri troubleshooting there’s https://discord.gg/SpmNs4S

**Comment by Jaden-Giordano** [comment]
That works with me if yall are okay with it. I have another PR in the works, based of my PR, for following better styling practices. I can keep working off my branches, but I'm sure it'll become a mess eventually just branching of the same PR over and over again.

**Comment by erlend-sh** [comment]
Great! You’ve been granted maintainer permissions.
